import type { Metadata } from "next";
import LegalPage from "@/components/legal/LegalPage";

export const metadata: Metadata = { title: "Terms of Service | OnyxIntel" };

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" effectiveDate="August 14, 2026">
      <section><h2>1. Agreement and authorized use</h2><p>These terms govern access to OnyxIntel. You must be authorized by the organization whose workspace, projects, and records you use. You are responsible for activity performed through your account and for keeping access credentials secure.</p></section>
      <section><h2>2. Construction decisions remain human decisions</h2><p>OnyxIntel assists with document review, takeoff, estimating, scheduling, project controls, and related workflows. It does not replace licensed design professionals, code officials, legal or financial advisers, qualified estimators, competent persons, or required field verification.</p><p>AI can make mistakes and may omit, duplicate, or misclassify scope, quantities, pricing, requirements, and risks. Outputs marked provisional, inferred, uncertified, or unapproved must not be treated as authoritative. You must verify current drawings, specifications, addenda, site conditions, codes, contracts, quotes, calculations, assumptions, and exclusions before approval, bidding, procurement, contracting, or field use.</p></section>
      <section><h2>3. Your data and permissions</h2><p>You retain rights in content you submit. You grant OnyxIntel the limited rights needed to host, process, analyze, and return that content to provide and secure the service. You represent that you have permission to upload and process project documents and personal information. You control who is invited to your workspace and must assign appropriate roles.</p></section>
      <section><h2>4. Acceptable use</h2><ul><li>Do not access another tenant&apos;s data or bypass approval, security, or usage controls.</li><li>Do not upload unlawful content, malware, or content you lack permission to use.</li><li>Do not use AI outputs as fabricated evidence, professional certification, or a substitute for legally required review.</li><li>Do not reverse engineer, overload, scrape, or disrupt the service.</li></ul></section>
      <section><h2>5. Estimates, prices, and integrations</h2><p>Market prices, productivity rates, schedules, and forecasts change and are project-specific. A displayed value is only as current and reliable as its cited evidence. Third-party services may have separate terms and availability. You remain responsible for quote acceptance, profitability floors, taxes, contracts, payments, and external communications.</p></section>
      <section><h2>6. Fees and cancellation</h2><p>Paid features are billed under the plan shown at checkout. Taxes may apply. Unless a separate written agreement states otherwise, subscriptions renew for the selected period and may be canceled for future renewal through the billing portal. Previously incurred charges and usage remain payable.</p></section>
      <section><h2>7. Availability and changes</h2><p>We work to keep the service reliable but do not guarantee uninterrupted availability. Features may change to improve safety, accuracy, security, or compliance. Emergency-continuity tools remain subject to the same permissions and verification requirements.</p></section>
      <section><h2>8. Disclaimers and liability</h2><p>To the extent permitted by law, the service is provided without warranties of fitness for a particular project outcome, error-free operation, or complete document interpretation. OnyxIntel is not responsible for losses caused by unverified outputs, inaccurate source material, unauthorized access caused by your credential handling, or third-party services. Any liability limitations in an executed order form or master agreement also apply.</p></section>
      <section><h2>9. Suspension and termination</h2><p>Access may be suspended for security threats, nonpayment, unlawful use, or material violation of these terms. You may stop using the service at any time. Data export and deletion are handled according to your plan, contract, legal obligations, and the Privacy Notice.</p></section>
      <section><h2>10. Contact and controlling agreement</h2><p>Questions or legal notices should be sent through your OnyxIntel account administrator or the official support channel provided with your subscription. If your organization has a signed agreement with OnyxIntel, that agreement controls where it conflicts with these online terms.</p></section>
    </LegalPage>
  );
}
