/**
 * Automated Bid Omission & Risk Scanner
 * ---------------------------------------
 * Cross-references plan notes / schedule callouts against expected CSI
 * companion scopes (and optionally pgvector `match_chunks` hits). Flags
 * missing scope (e.g. concrete without rebar/vapor barrier) and drafts a
 * client-ready RFI via ai_agent_audit_trails — never auto-sends.
 */

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type SupabaseAnyClient = any;

export interface PlanFinding {
  description: string;
  cost_code?: string | null;
  quantity?: number;
  unit?: string;
  source?: string;
  sheet_ref?: string | null;
  raw_text?: string;
}

export interface OmissionFlag {
  finding: string;
  expected_companions: string[];
  missing: string[];
  severity: "high" | "medium" | "low";
  sheet_ref?: string | null;
  rfi_subject: string;
  rfi_body: string;
  spec_hits?: Array<{ content: string; similarity?: number }>;
}

interface RunArgs {
  db: SupabaseAnyClient;
  tenantId: string;
  projectId: string;
  documentId?: string | null;
  findings: PlanFinding[];
  /** Optional precomputed embedding for RAG against CSI/spec chunks. */
  queryEmbedding?: number[] | null;
}

/** CSI companion expectations — when A appears, B/C should usually appear. */
const COMPANION_RULES: Array<{
  when: RegExp;
  whenCode?: RegExp;
  expect: Array<{ label: string; match: RegExp; codePrefix?: string }>;
  severity: OmissionFlag["severity"];
}> = [
  {
    when: /\b(concrete|slab|footing|foundation|cip)\b/i,
    whenCode: /^03-/,
    expect: [
      { label: "rebar / reinforcement", match: /\b(rebar|reinforc|#\d\s*bar)\b/i, codePrefix: "03-20" },
      { label: "vapor barrier", match: /\b(vapor\s*barrier|vapour\s*barrier|underslab\s*membrane)\b/i, codePrefix: "07-26" },
      { label: "formwork", match: /\b(formwork|forms?|form\s*tie)\b/i, codePrefix: "03-11" },
    ],
    severity: "high",
  },
  {
    when: /\b(asphalt|paving|pavement)\b/i,
    whenCode: /^32-1/,
    expect: [
      { label: "aggregate base", match: /\b(aggregate\s*base|crushed\s*rock|base\s*course)\b/i, codePrefix: "32-11" },
      { label: "prime / tack coat", match: /\b(prime\s*coat|tack\s*coat)\b/i },
    ],
    severity: "medium",
  },
  {
    when: /\b(pipe|sewer|storm\s*drain|water\s*main)\b/i,
    whenCode: /^33-/,
    expect: [
      { label: "trench excavation / bedding", match: /\b(excavation|bedding|backfill|trench)\b/i, codePrefix: "31-23" },
      { label: "testing", match: /\b(pressure\s*test|deflection|mandrel|leakage\s*test)\b/i },
    ],
    severity: "high",
  },
  {
    when: /\b(roofing|tpo|epdm|membrane\s*roof)\b/i,
    whenCode: /^07-5/,
    expect: [
      { label: "insulation", match: /\b(insulation|iso\s*board|polyiso)\b/i, codePrefix: "07-21" },
      { label: "flashing", match: /\b(flashing|counterflash)\b/i },
    ],
    severity: "medium",
  },
];

function corpusText(findings: PlanFinding[]): string {
  return findings
    .map((f) => `${f.cost_code ?? ""} ${f.description} ${f.raw_text ?? ""}`)
    .join("\n")
    .toLowerCase();
}

function hasCompanion(
  corpus: string,
  findings: PlanFinding[],
  rule: { match: RegExp; codePrefix?: string },
): boolean {
  if (rule.match.test(corpus)) return true;
  if (rule.codePrefix) {
    return findings.some((f) => (f.cost_code || "").startsWith(rule.codePrefix!));
  }
  return false;
}

export function scanOmissions(
  findings: PlanFinding[],
  specHits: Array<{ content: string; similarity?: number }> = [],
): OmissionFlag[] {
  if (!findings.length) return [];
  const corpus = corpusText(findings);
  const flags: OmissionFlag[] = [];

  for (const rule of COMPANION_RULES) {
    const triggers = findings.filter(
      (f) =>
        rule.when.test(f.description) ||
        rule.when.test(f.raw_text || "") ||
        (rule.whenCode && rule.whenCode.test(f.cost_code || "")),
    );
    if (!triggers.length) continue;

    const missing = rule.expect
      .filter((e) => !hasCompanion(corpus, findings, e))
      .map((e) => e.label);
    if (!missing.length) continue;

    const sample = triggers[0];
    const sheet = sample.sheet_ref || "plans";
    const subject = `Missing scope companions for ${sample.description.slice(0, 80)}`;
    const body = [
      `We identified ${sample.description} on ${sheet}`,
      sample.cost_code ? `(CSI ${sample.cost_code})` : "",
      `but the bid package / schedule callouts do not clearly include:`,
      ...missing.map((m) => `  • ${m}`),
      "",
      "Please confirm whether these items are:",
      "  1) By owner / NIC",
      "  2) Included under another specification section (cite section)",
      "  3) To be added by addendum",
      "",
      "This RFI is generated by the Onyx bid-omission scanner for estimator review.",
    ]
      .filter(Boolean)
      .join("\n");

    flags.push({
      finding: sample.description,
      expected_companions: rule.expect.map((e) => e.label),
      missing,
      severity: rule.severity,
      sheet_ref: sample.sheet_ref,
      rfi_subject: subject,
      rfi_body: body,
      spec_hits: specHits.slice(0, 3),
    });
  }

  return flags;
}

export async function runBidOmissionScanner({
  db,
  tenantId,
  projectId,
  documentId,
  findings,
  queryEmbedding,
}: RunArgs): Promise<{ flagged: number; flags: OmissionFlag[] }> {
  let specHits: Array<{ content: string; similarity?: number }> = [];
  if (queryEmbedding && queryEmbedding.length > 0) {
    const vectorStr = `[${queryEmbedding.join(",")}]`;
    const { data } = await db.rpc("match_chunks", {
      query_embedding: vectorStr,
      match_count: 8,
      filter_tenant_id: tenantId,
      filter_project_id: projectId,
    });
    if (Array.isArray(data)) {
      specHits = data.map((row: { content?: string; similarity?: number }) => ({
        content: String(row.content ?? "").slice(0, 500),
        similarity: typeof row.similarity === "number" ? row.similarity : undefined,
      }));
    }
  }

  const flags = scanOmissions(findings, specHits);
  if (!flags.length) return { flagged: 0, flags: [] };

  let inserted = 0;
  for (const flag of flags) {
    const { error } = await db.from("ai_agent_audit_trails").insert({
      tenant_id: tenantId,
      project_id: projectId,
      document_id: documentId ?? null,
      agent_name: "bid_omission_scanner",
      execution_trigger: "bid_risk_scan",
      finding_summary: flag.rfi_subject,
      recommendations: {
        action: "draft_rfi",
        subject: flag.rfi_subject,
        body: flag.rfi_body,
        severity: flag.severity,
        missing: flag.missing,
        finding: flag.finding,
        sheet_ref: flag.sheet_ref,
        spec_hits: flag.spec_hits,
      },
      severity: flag.severity === "high" ? "critical" : flag.severity === "medium" ? "warning" : "info",
      status: "pending_human_review",
    });
    if (!error) inserted += 1;
  }

  return { flagged: inserted, flags };
}
